### ISSUE TITLE
Keywords' Unreadable Error on Opportunities Page

### ISSUE THREAD

**Issue by Darren-lin** [mikeriepe/amplifytasselapp#56]
**Description:**

On some occasions, when visiting the Opportunities page, there is an error. The error message reads, "Cannot read 'keywords'". This issue appears sporadically, and it is resolved by refreshing the page.

**Possible Solutions:**

It is suspected that this issue might be tied to the asynchronous loading of data. It might occur when the page attempts to read the 'keywords' before they have been fully loaded.

**Comment by danielchandg** [comment]
Fixed in branch `userAuth`.
- **Problem:** AuthContext only rendered once. If the user logged in, AuthContext still contained `null` values for `user` and `userContext`.
- **Solution:** When the user logs in, the useEffect in AuthContext is triggered. `user` and `userContext` are updated appropriately with the user's info.
